@URL = http://localhost:3000

### Listar pets para adoção
GET {{URL}}/pets/available 
Accept: application/json

### Listar todos usuarios
GET {{URL}}/user/
Accept: application/json

### Ver dados de um usuario
GET {{URL}}/users/:id
Accept: application/json

### Listar todos os pets
GET {{URL}}/pets/
Accept: application/json

### Listar dados de um pet
GET {{URL}}/pets/:id
Accept: application/json

### Listar dados de um pet
GET {{URL}}/adoptions
Accept: application/json

### Cadastra um novo usuário (adopter ou admin)
POST {{URL}}/users 
Content-Type: application/json

{

}

### Login
POST {{URL}}/login
Content-Type: application/json

{

}

### Cadastra novo pet 
POST {{URL}}/pets
Content-Type: application/json

{

}

### Realiza a adoção de um pet
POST {{URL}}/pets
Content-Type: application/json

{

}


### Atualiza dados do usuário
PUT {{URL}}/users/:id
Content-Type: application/json

{

}

### Atualiza os dados de um pet
PUT {{URL}}/pets/:id 
Content-Type: application/json

{

}

### Remove um usuário 
DELETE {{URL}}/user/:id

### Remove um pet do sistema
DELETE {{URL}}/pets/:id
